#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

bindkey "^R" history-incremental-search-backward
setopt INTERACTIVE_COMMENTS

bindkey '^[[1;5D' vi-backward-word
bindkey '^[[1;5C' vi-forward-word

# Source custom RC per machine
if [[ -s "${ZDOTDIR:-$HOME}/.zshrclocal" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrclocal"
fi

unsetopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt nocdablevars

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

# Deepmind Bash RC
[[ -e ~/.profile ]] && emulate sh -c 'source /google/data/ro/teams/deepmind-eng/config/bashrc' > /dev/null

# Setup CUDA and GPU
# nvsetup # Only iff /dev/nvidia-uvm doesn't exist
export CUDA_BIN_PATH=/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

# Setup texlive
export PATH=$PATH:/opt/texbin

# Fix TMUX pretty
alias tmux="TERM=screen-256color-bce tmux"
